### ISSUE TITLE
Missing fill items causing crash `java.lang.IllegalArgumentException: bound must be positive`

### ISSUE THREAD

**Issue by Ascranima** [MarkusBordihn/BOs-Daily-Rewards#5]
**Describe the bug**
I've just configurated the server file but it just doesnt works, Maybe i have an error on the file config or doing something wrong. 
The readme file doesnt specify if it have a certain order, which spaces can be left blank or if it is compatible with mods.

[daily_rewards-common.txt](https://github.com/MarkusBordihn/BOs-Daily-Rewards/files/9612316/daily_rewards-common.txt)

thanks in advance if you can help me with this! It is a great mod, just i dont know how to make it work for me!

**Comment by MarkusBordihn** [comment]
Thanks for the report, it seems you have removed all fill items, which will cause the following crash on my test instance.
```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at de.markusbordihn.dailyrewards.rewards.Rewards.calculateRewardItemsForMonth(Rewards.java:116)
```

I will release a fix for this, which will use minecraft:dirt as fallback in this specific case, otherwise the config looks fine for me.
You should define at least 1-2 fill items just in the case of an leap year or any other edge case were an reward item is missing.

Most of the mod items should be supported out of the box.
Every item which is not compatible or if the required mod is not installed will be automatically skipped like:
```
[21Sep2022 22:39:24.041] [Server thread/INFO] [Daily Rewards/]: Calculate Reward items for month 9 with 30 days ...
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item torchmaster:megatorch in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item reliquary:glowing_bread in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item gobber2:gobber2_sword in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item usefulbackpacks:backpack_enderchest in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item naturalist:reddy_bear in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item alexmobs:spawn_egg_capuchin_monkey in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item reliquary:glowing_bread in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item reliquary:angelheart_vial in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item artifacts:whoopee_cushion in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item alexmobs:banana in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item reliquary:glowing_bread in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item hammers:enhanced_netherite_hammer in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item artifacts:helium_flamingo in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item supplementaries:bomb in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item reliquary:glowing_bread in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item artifacts:eternal_steak in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item mob_catcher:diamond_mob_catcher in the registry!
[21Sep2022 22:39:24.042] [Server thread/WARN] [Daily Rewards/]: Unable to find reward item gobber2:gobber2_sword_nether in the registry!
[21Sep2022 22:39:24.042] [Server thread/INFO] [Daily Rewards/]: Found 17 missing days without any items, will try to use fill items ...
```
